import { useEffect, useMemo, useState } from 'react';
import { Socket } from 'socket.io-client';
import RoomCreateModal from './RoomCreateModal';
import ArchivedGames from './ArchivedGames';

export default function Lobby({ socket, rooms, archives, playerId }: { socket: Socket | null; rooms: any[]; archives: any; playerId: string }) {
  const [open, setOpen] = useState(false); const [joinRoomId, setJoinRoomId] = useState(''); const [displayName, setDisplayName] = useState(localStorage.getItem('xiangqi_viet_name') || 'Anh Linh'); const [password, setPassword] = useState(''); const [asSpectator, setAsSpectator] = useState(false);
  useEffect(() => { const id = new URLSearchParams(location.search).get('room'); if (id) setJoinRoomId(id); socket?.emit('archive:list'); }, [socket]);
  const canJoin = useMemo(() => joinRoomId.trim().length >= 4 && displayName.trim().length >= 2, [joinRoomId, displayName]);
  const join = (id = joinRoomId) => { localStorage.setItem('xiangqi_viet_name', displayName); socket?.emit('room:join', { roomId: id, playerId, displayName, password, asSpectator, side: 'auto' }); };
  const fmt = (r: any) => r.timeControl?.mode === 'none' ? 'Không giờ' : `${Math.round(r.timeControl.initialMs / 60000)}p${r.timeControl.incrementMs ? ' + ' + r.timeControl.incrementMs / 1000 + 's' : ''}`;
  return <main className="lobby"><section className="hero card"><h1>Cờ Tướng Việt - Trí Tuệ Việt</h1><p>Chơi Cờ Tướng hoặc Cờ Úp online Người vs Người qua link. Có đồng hồ, chat, hoàn cờ, tỷ số bàn, lưu ván và xem lại lịch sử nước đi.</p><div className="actions"><button onClick={() => setOpen(true)}>Tạo bàn mới</button><button className="secondary" onClick={() => { socket?.emit('room:list'); socket?.emit('archive:list'); }}>Làm mới</button></div></section><section className="card join-box"><h2>Vào bàn bằng mã</h2><div className="grid-2"><input value={displayName} onChange={e => setDisplayName(e.target.value)} placeholder="Tên hiển thị 2-20 ký tự"/><input value={joinRoomId} onChange={e => setJoinRoomId(e.target.value.toUpperCase())} placeholder="Mã bàn"/><input value={password} onChange={e => setPassword(e.target.value)} placeholder="Mật khẩu nếu có"/><label className="check"><input type="checkbox" checked={asSpectator} onChange={e => setAsSpectator(e.target.checked)}/> Vào xem</label></div><button disabled={!canJoin} onClick={() => join()}>Vào bàn</button></section><section className="card"><h2>Bàn đang mở</h2><div className="room-list">{rooms.length === 0 && <p className="muted">Chưa có bàn công khai.</p>}{rooms.map(r => <button className="room-row" key={r.id} onClick={() => { setJoinRoomId(r.id); join(r.id); }}><strong>{r.name}</strong><span>Mã {r.id} · {r.gameMode === 'dark' ? 'Cờ Úp' : 'Cờ Tướng'} · {fmt(r)} · {r.status === 'playing' ? 'Đang chơi' : 'Chờ'}</span><span>Đỏ: {r.redName || 'trống'} · Đen: {r.blackName || 'trống'} · Xem: {r.spectatorCount}</span>{r.hasPassword && <em>Có mật khẩu</em>}</button>)}</div></section><ArchivedGames socket={socket} archives={archives}/>{open && <RoomCreateModal socket={socket} playerId={playerId} onClose={() => setOpen(false)}/>}</main>;
}
